site:
  build: site
  # links:
  #   - mysql
  volumes:
    # Source
    - ~/src/site/:/opt/site/current/
    # Virtual env
    - /opt/site/docker-venv/:/opt/site/current/venv/
    # Ansible stuff dir
    - ~/src/site_deploy/site/ansible/:/opt/site/ansible/
    # Home dir
    - /opt/site/home/:/root/

    # # Logs
    # - ~/src/site/log/:/var/log
  ports:
    - "0.0.0.0:80:80"
  command: 'bash /opt/site/startserver.sh'